// ============================================================================
// Node Definitions — Full catalog (Weavy-compatible)
// status: 'active' = çalışıyor | 'beta' = test aşaması | 'soon' = yakında
// ============================================================================

export type NodeDataType = 'text' | 'image' | 'video' | 'audio' | 'mask' | 'number' | 'boolean' | 'array' | '3d' | 'any'
export type NodeStatus = 'active' | 'beta' | 'soon'

export interface PortDef {
  name: string
  type: NodeDataType
  required?: boolean
  multiple?: boolean
}

export interface NodeDefinition {
  id: string                   // node type key (matches ReactFlow nodeTypes)
  label: string                // display name
  description: string
  icon: string                 // emoji icon
  category: NodeCategory
  subcategory: string
  inputs: PortDef[]
  outputs: PortDef[]
  provider?: string            // AI provider name
  creditCost?: number | string // fixed or 'varies'
  status: NodeStatus
  isNew?: boolean
}

export type NodeCategory =
  | 'toolbox'
  | 'text'
  | 'image-gen'
  | 'image-edit'
  | 'image-enhance'
  | 'video-gen'
  | 'video-edit'
  | 'audio'
  | '3d'
  | 'helpers'
  | 'iterators'
  | 'datatypes'
  | 'production'  // Creavidy-specific CapCut-style nodes

export interface CategoryMeta {
  id: NodeCategory
  label: string
  icon: string
  color: string
}

export const CATEGORY_META: CategoryMeta[] = [
  { id: 'production',     label: 'Production',     icon: '🎬', color: '#f59e0b' },
  { id: 'text',           label: 'Text & Prompts', icon: '📝', color: '#a78bfa' },
  { id: 'image-gen',      label: 'Image Gen',      icon: '🖼️',  color: '#FFE744' },
  { id: 'image-edit',     label: 'Image Edit',     icon: '✏️',  color: '#f43f5e' },
  { id: 'image-enhance',  label: 'Enhance',        icon: '✨', color: '#10b981' },
  { id: 'video-gen',      label: 'Video Gen',      icon: '🎥', color: '#D1FE17' },
  { id: 'video-edit',     label: 'Video Edit',     icon: '🎞️',  color: '#0ea5e9' },
  { id: 'audio',          label: 'Audio',          icon: '🎙️',  color: '#ec4899' },
  { id: '3d',             label: '3D Models',      icon: '🧊', color: '#06b6d4' },
  { id: 'toolbox',        label: 'Toolbox',        icon: '🔧', color: '#6366f1' },
  { id: 'helpers',        label: 'Helpers',        icon: '⚡', color: '#84cc16' },
  { id: 'iterators',      label: 'Iterators',      icon: '🔁', color: '#f97316' },
  { id: 'datatypes',      label: 'Data Types',     icon: '📦', color: '#94a3b8' },
]

// ─── NODE CATALOG ─────────────────────────────────────────────────────────────

export const NODE_DEFINITIONS: NodeDefinition[] = [

  // ── PRODUCTION (Creavidy CapCut-style) ──────────────────────────────────────
  {
    id: 'videoBriefNode',
    label: 'Video Brief',
    description: 'Videonun hikayesini, stilini ve seslendiricisini ayarla',
    icon: '🎬',
    category: 'production',
    subcategory: 'brief',
    inputs: [],
    outputs: [{ name: 'Brief', type: 'text' }],
    status: 'active',
  },
  {
    id: 'filmStripNode',
    label: 'Film Strip',
    description: 'Sahne bazlı video üretim şeridi — görsel + ses + altyazı',
    icon: '🎞️',
    category: 'production',
    subcategory: 'strip',
    inputs: [{ name: 'Brief', type: 'text' }],
    outputs: [{ name: 'Video', type: 'video' }],
    status: 'active',
  },

  // ── TEXT & PROMPTS ───────────────────────────────────────────────────────────
  {
    id: 'scriptNode',
    label: 'Script',
    description: 'AI ile senaryo veya metin üret',
    icon: '📄',
    category: 'text',
    subcategory: 'generate',
    inputs: [],
    outputs: [{ name: 'Text', type: 'text' }],
    creditCost: 2,
    status: 'active',
  },
  {
    id: 'llmNode',
    label: 'Any LLM',
    description: 'GPT-4o, Gemini, Claude ile serbest LLM çağrısı',
    icon: '🤖',
    category: 'text',
    subcategory: 'generate',
    inputs: [{ name: 'Prompt', type: 'text' }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Text', type: 'text' }],
    creditCost: 3,
    status: 'active',
  },
  {
    id: 'promptEnhancerNode',
    label: 'Prompt Enhancer',
    description: "AI ile promptu iyileştir ve zenginleştir",
    icon: '✨',
    category: 'text',
    subcategory: 'enhance',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Text', type: 'text' }],
    creditCost: 1,
    status: 'soon',
  },
  {
    id: 'imageDescriberNode',
    label: 'Image Describer',
    description: 'Görseli metne dönüştür (vision model)',
    icon: '👁️',
    category: 'text',
    subcategory: 'vision',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Text', type: 'text' }],
    creditCost: 2,
    status: 'soon',
  },
  {
    id: 'videoDescriberNode',
    label: 'Video Describer',
    description: 'Videoyu metne dönüştür',
    icon: '🎬',
    category: 'text',
    subcategory: 'vision',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [{ name: 'Text', type: 'text' }],
    creditCost: 3,
    status: 'soon',
  },
  {
    id: 'promptConcatNode',
    label: 'Prompt Concatenator',
    description: "Birden fazla promptu birleştir",
    icon: '🔗',
    category: 'text',
    subcategory: 'utility',
    inputs: [{ name: 'Text 1', type: 'text', required: true, multiple: true }],
    outputs: [{ name: 'Text', type: 'text' }],
    status: 'soon',
  },
  {
    id: 'systemPromptNode',
    label: 'System Prompt',
    description: 'LLM için sistem talimatı tanımla',
    icon: '⚙️',
    category: 'text',
    subcategory: 'utility',
    inputs: [],
    outputs: [{ name: 'System', type: 'text' }],
    status: 'active',
  },

  // ── IMAGE GENERATION ─────────────────────────────────────────────────────────
  {
    id: 'imageGenNode',
    label: 'Flux Schnell',
    description: 'Hızlı görsel üretim — Flux Schnell',
    icon: '⚡',
    category: 'image-gen',
    subcategory: 'flux',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 5,
    status: 'active',
  },
  {
    id: 'fluxProNode',
    label: 'Flux Pro',
    description: 'Yüksek kaliteli görsel — Flux Pro 1.1',
    icon: '🖼️',
    category: 'image-gen',
    subcategory: 'flux',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 10,
    status: 'active',
  },
  {
    id: 'flux2ProNode',
    label: 'Flux 2 Pro',
    description: 'En kaliteli Flux — Flux 2 Pro Ultra',
    icon: '💎',
    category: 'image-gen',
    subcategory: 'flux',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 15,
    status: 'active',
  },
  {
    id: 'recraftV4Node',
    label: 'Recraft V4',
    description: 'Profesyonel görsel & illüstrasyon — Recraft V4',
    icon: '🎨',
    category: 'image-gen',
    subcategory: 'recraft',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Recraft',
    creditCost: 12,
    status: 'active',
    isNew: true,
  },
  {
    id: 'imagen4Node',
    label: 'Imagen 4',
    description: "Google'un en yeni görsel modeli",
    icon: '🌈',
    category: 'image-gen',
    subcategory: 'google',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Google',
    creditCost: 12,
    status: 'soon',
    isNew: true,
  },
  {
    id: 'gptImage15Node',
    label: 'GPT Image 1.5',
    description: "OpenAI'ın yeni görsel modeli",
    icon: '🟢',
    category: 'image-gen',
    subcategory: 'openai',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'OpenAI',
    creditCost: 15,
    status: 'soon',
    isNew: true,
  },
  {
    id: 'sd35Node',
    label: 'Stable Diffusion 3.5',
    description: "Stability AI'ın SD 3.5 modeli",
    icon: '🌀',
    category: 'image-gen',
    subcategory: 'stability',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Stability AI',
    creditCost: 8,
    status: 'active',
  },
  {
    id: 'ideogramV3Node',
    label: 'Ideogram V3',
    description: 'Metin render desteğiyle görsel üretim',
    icon: '🔠',
    category: 'image-gen',
    subcategory: 'ideogram',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Ideogram',
    creditCost: 10,
    status: 'active',
  },
  {
    id: 'seedream5LiteNode',
    label: 'Seedream 5.0',
    description: 'Seedream 5.0 Lite — hızlı ve kaliteli',
    icon: '🌱',
    category: 'image-gen',
    subcategory: 'bytedance',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'ByteDance',
    creditCost: 6,
    status: 'active',
  },

  // ── IMAGE EDITING ─────────────────────────────────────────────────────────────
  {
    id: 'fluxKontextNode',
    label: 'Flux Kontext',
    description: 'Metin ile görsel düzenleme — Flux Kontext',
    icon: '✏️',
    category: 'image-edit',
    subcategory: 'flux',
    inputs: [{ name: 'Image', type: 'image', required: true }, { name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 10,
    status: 'active',
  },
  {
    id: 'inpaintNode',
    label: 'Inpaint',
    description: 'Maske ile bölgesel düzenleme — Flux Fill Pro',
    icon: '🖌️',
    category: 'image-edit',
    subcategory: 'mask',
    inputs: [{ name: 'Image', type: 'image', required: true }, { name: 'Mask', type: 'mask', required: true }, { name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 12,
    status: 'beta',
  },
  {
    id: 'outpaintNode',
    label: 'Outpaint',
    description: 'Görsel sınırlarını genişlet — Flux Pro Outpaint',
    icon: '📐',
    category: 'image-edit',
    subcategory: 'extend',
    inputs: [{ name: 'Image', type: 'image', required: true }, { name: 'Prompt', type: 'text', required: false }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Black Forest Labs',
    creditCost: 12,
    status: 'soon',
  },
  {
    id: 'removeBgNode',
    label: 'Remove BG',
    description: 'Arka planı otomatik kaldır',
    icon: '🔲',
    category: 'image-edit',
    subcategory: 'mask',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'fal.ai',
    creditCost: 3,
    status: 'beta',
  },
  {
    id: 'replaceBgNode',
    label: 'Replace BG',
    description: 'Arka planı yeni bir prompt ile değiştir',
    icon: '🌄',
    category: 'image-edit',
    subcategory: 'extend',
    inputs: [{ name: 'Image', type: 'image', required: true }, { name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'fal.ai',
    creditCost: 8,
    status: 'soon',
  },
  {
    id: 'virtualTryOnNode',
    label: 'Virtual Try-On',
    description: 'Kıyafet sanal deneme — Kolors',
    icon: '👗',
    category: 'image-edit',
    subcategory: 'special',
    inputs: [{ name: 'Person', type: 'image', required: true }, { name: 'Garment', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Kwai',
    creditCost: 15,
    status: 'soon',
  },
  {
    id: 'painterNode',
    label: 'Painter',
    description: 'El ile çizim / boyama aracı',
    icon: '🎨',
    category: 'toolbox',
    subcategory: 'editing',
    inputs: [{ name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'cropNode',
    label: 'Crop',
    description: 'Görsel kırpma',
    icon: '✂️',
    category: 'toolbox',
    subcategory: 'editing',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'resizeNode',
    label: 'Resize',
    description: 'Boyut değiştirme',
    icon: '⤢',
    category: 'toolbox',
    subcategory: 'editing',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'compositorNode',
    label: 'Compositor',
    description: 'Çoklu katman birleştirme',
    icon: '🗂️',
    category: 'toolbox',
    subcategory: 'editing',
    inputs: [{ name: 'Image', type: 'image', required: true, multiple: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'compareNode',
    label: 'Compare',
    description: 'İki görseli yan yana karşılaştır',
    icon: '⚖️',
    category: 'toolbox',
    subcategory: 'editing',
    inputs: [{ name: 'Image A', type: 'image', required: true }, { name: 'Image B', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
    isNew: true,
  },
  {
    id: 'maskExtractorNode',
    label: 'Mask Extractor',
    description: 'Otomatik nesne maskesi çıkar',
    icon: '🔍',
    category: 'toolbox',
    subcategory: 'matte',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Mask', type: 'mask' }],
    status: 'soon',
  },
  {
    id: 'maskByTextNode',
    label: 'Mask by Text',
    description: 'Metin ile maske oluştur (SAM)',
    icon: '🔤',
    category: 'toolbox',
    subcategory: 'matte',
    inputs: [{ name: 'Image', type: 'image', required: true }, { name: 'Text', type: 'text', required: true }],
    outputs: [{ name: 'Mask', type: 'mask' }],
    status: 'soon',
  },
  {
    id: 'depthAnyV2Node',
    label: 'Depth Map',
    description: 'Derinlik haritası çıkar — Depth Anything V2',
    icon: '📊',
    category: 'toolbox',
    subcategory: 'analysis',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
    isNew: true,
  },

  // ── IMAGE ENHANCE ─────────────────────────────────────────────────────────────
  {
    id: 'upscaleNode',
    label: 'Upscale',
    description: 'Görsel çözünürlüğünü artır — Real-ESRGAN',
    icon: '🔭',
    category: 'image-enhance',
    subcategory: 'upscale',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'fal.ai',
    creditCost: 5,
    status: 'beta',
  },
  {
    id: 'topazUpscaleNode',
    label: 'Topaz Upscale',
    description: 'Topaz AI ile profesyonel upscale',
    icon: '💠',
    category: 'image-enhance',
    subcategory: 'upscale',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Topaz Labs',
    creditCost: 8,
    status: 'soon',
  },
  {
    id: 'magnificUpscaleNode',
    label: 'Magnific Upscale',
    description: 'Magnific AI — detay zenginleştirme',
    icon: '🔬',
    category: 'image-enhance',
    subcategory: 'upscale',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    provider: 'Magnific',
    creditCost: 10,
    status: 'soon',
  },

  // ── VIDEO GENERATION ──────────────────────────────────────────────────────────
  {
    id: 'videoGenNode',
    label: 'Kling 3.0',
    description: 'Kling 3.0 ile metin/görsel → video',
    icon: '🎥',
    category: 'video-gen',
    subcategory: 'kling',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Kuaishou',
    creditCost: 30,
    status: 'active',
    isNew: true,
  },
  {
    id: 'veo3Node',
    label: 'Veo 3.1',
    description: 'Google Veo 3.1 — sinematik video üretim',
    icon: '🔮',
    category: 'video-gen',
    subcategory: 'google',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Google',
    creditCost: 50,
    status: 'active',
  },
  {
    id: 'sora2Node',
    label: 'Sora 2 Pro',
    description: 'OpenAI Sora 2 — yüksek kaliteli video',
    icon: '🌊',
    category: 'video-gen',
    subcategory: 'openai',
    inputs: [{ name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'OpenAI',
    creditCost: 60,
    status: 'active',
  },
  {
    id: 'runwayGen4Node',
    label: 'Runway Gen-4',
    description: 'Runway Gen-4 — sinematik kalite',
    icon: '🛫',
    category: 'video-gen',
    subcategory: 'runway',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Runway',
    creditCost: 40,
    status: 'soon',
  },
  {
    id: 'lumaRay2Node',
    label: 'Luma Ray 2',
    description: 'Luma Dream Machine Ray 2',
    icon: '💡',
    category: 'video-gen',
    subcategory: 'luma',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Luma AI',
    creditCost: 25,
    status: 'active',
  },
  {
    id: 'minimaxHailuoNode',
    label: 'Minimax Hailuo',
    description: 'Minimax Hailuo-02 video modeli',
    icon: '🌀',
    category: 'video-gen',
    subcategory: 'minimax',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Minimax',
    creditCost: 25,
    status: 'active',
  },
  {
    id: 'wan26Node',
    label: 'Wan 2.6',
    description: 'Alibaba Wan 2.6 video modeli',
    icon: '🌊',
    category: 'video-gen',
    subcategory: 'alibaba',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Alibaba',
    creditCost: 20,
    status: 'active',
  },
  {
    id: 'hunyuanNode',
    label: 'Hunyuan',
    description: 'Tencent Hunyuan video modeli',
    icon: '🐉',
    category: 'video-gen',
    subcategory: 'tencent',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Tencent',
    creditCost: 22,
    status: 'active',
  },
  {
    id: 'ltx23Node',
    label: 'LTX 2.3',
    description: 'LTX Video 2.3 — hızlı video',
    icon: '⚡',
    category: 'video-gen',
    subcategory: 'ltx',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'LTX',
    creditCost: 15,
    status: 'active',
  },

  // ── VIDEO EDITING ─────────────────────────────────────────────────────────────
  {
    id: 'lipSyncNode',
    label: 'Lip Sync',
    description: 'Ses dosyasına dudak senkronizasyonu — Sync 2 Pro',
    icon: '👄',
    category: 'video-edit',
    subcategory: 'lipsync',
    inputs: [{ name: 'Video', type: 'video', required: true }, { name: 'Audio', type: 'audio', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Sync Labs',
    creditCost: 20,
    status: 'soon',
  },
  {
    id: 'videoUpscaleNode',
    label: 'Video Upscale',
    description: 'Video çözünürlüğünü artır — Topaz',
    icon: '🔭',
    category: 'video-edit',
    subcategory: 'enhance',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Topaz Labs',
    creditCost: 15,
    status: 'soon',
  },
  {
    id: 'videoV2VNode',
    label: 'Video to Video',
    description: 'Videoyu stil transferiyle dönüştür — Wan Vace',
    icon: '🔄',
    category: 'video-edit',
    subcategory: 'transform',
    inputs: [{ name: 'Video', type: 'video', required: true }, { name: 'Prompt', type: 'text', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    provider: 'Alibaba',
    creditCost: 30,
    status: 'soon',
  },
  {
    id: 'extractFrameNode',
    label: 'Extract Frame',
    description: 'Videodan belirli kare çıkar',
    icon: '📸',
    category: 'video-edit',
    subcategory: 'utility',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'videoConcatNode',
    label: 'Video Concat',
    description: 'Birden fazla videoyu birleştir',
    icon: '➕',
    category: 'video-edit',
    subcategory: 'utility',
    inputs: [{ name: 'Video', type: 'video', required: true, multiple: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    status: 'soon',
  },

  // ── AUDIO ─────────────────────────────────────────────────────────────────────
  {
    id: 'voiceNode',
    label: 'Voice (TTS)',
    description: 'Metinden ses üret — OpenAI / ElevenLabs / fal',
    icon: '🎙️',
    category: 'audio',
    subcategory: 'tts',
    inputs: [{ name: 'Text', type: 'text', required: true }],
    outputs: [{ name: 'Audio', type: 'audio' }],
    creditCost: 5,
    status: 'active',
  },
  {
    id: 'mergeAudioVideoNode',
    label: 'Merge Audio+Video',
    description: 'Ses ve videoyu birleştir',
    icon: '🔀',
    category: 'audio',
    subcategory: 'utility',
    inputs: [{ name: 'Video', type: 'video', required: true }, { name: 'Audio', type: 'audio', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    status: 'soon',
  },
  {
    id: 'videoToAudioNode',
    label: 'Video to Audio',
    description: 'Videodan ses kanalını çıkar',
    icon: '🎵',
    category: 'audio',
    subcategory: 'utility',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [{ name: 'Audio', type: 'audio' }],
    status: 'soon',
  },

  // ── 3D MODELS ─────────────────────────────────────────────────────────────────
  {
    id: 'meshyV6Node',
    label: 'Meshy V6',
    description: 'Metin veya görselden 3D model üret',
    icon: '🧊',
    category: '3d',
    subcategory: 'generate',
    inputs: [{ name: 'Prompt', type: 'text', required: true }, { name: 'Image', type: 'image', required: false }],
    outputs: [{ name: '3D', type: '3d' }],
    provider: 'Meshy',
    creditCost: 25,
    status: 'soon',
  },
  {
    id: 'hunyuan3DNode',
    label: 'Hunyuan 3D',
    description: 'Tencent Hunyuan 3D V3',
    icon: '🐉',
    category: '3d',
    subcategory: 'generate',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: '3D', type: '3d' }],
    provider: 'Tencent',
    creditCost: 20,
    status: 'soon',
  },
  {
    id: 'trellis3DNode',
    label: 'Trellis 3D',
    description: 'Görselden 3D sahne üret — Trellis',
    icon: '🏗️',
    category: '3d',
    subcategory: 'generate',
    inputs: [{ name: 'Image', type: 'image', required: true }],
    outputs: [{ name: '3D', type: '3d' }],
    creditCost: 20,
    status: 'soon',
  },

  // ── HELPERS ──────────────────────────────────────────────────────────────────
  {
    id: 'captionNode',
    label: 'Caption',
    description: 'Videoya altyazı ekle',
    icon: '💬',
    category: 'helpers',
    subcategory: 'output',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    status: 'active',
  },
  {
    id: 'exportNode',
    label: 'Export',
    description: 'Dosyayı dışa aktar / indir',
    icon: '📤',
    category: 'helpers',
    subcategory: 'output',
    inputs: [{ name: 'Video', type: 'video', required: true }],
    outputs: [],
    status: 'active',
  },
  {
    id: 'routerNode',
    label: 'Router',
    description: 'Veriyi birden fazla hedefe dağıt',
    icon: '🔀',
    category: 'helpers',
    subcategory: 'flow',
    inputs: [{ name: 'Input', type: 'any', required: true }],
    outputs: [{ name: 'Output', type: 'any', multiple: true }],
    status: 'active',
  },
  {
    id: 'stickyNoteNode',
    label: 'Sticky Note',
    description: 'Canvas üzerine not ekle',
    icon: '📌',
    category: 'helpers',
    subcategory: 'annotation',
    inputs: [],
    outputs: [],
    status: 'soon',
  },

  // ── ITERATORS ─────────────────────────────────────────────────────────────────
  {
    id: 'textIteratorNode',
    label: 'Text Iterator',
    description: 'Metin listesini bölerek döngüyle işle',
    icon: '🔁',
    category: 'iterators',
    subcategory: 'loop',
    inputs: [{ name: 'Text', type: 'text', required: true }],
    outputs: [{ name: 'Item', type: 'text' }],
    status: 'active',
  },
  {
    id: 'imageIteratorNode',
    label: 'Image Iterator',
    description: 'Görsel seti üzerinde döngü',
    icon: '🖼️',
    category: 'iterators',
    subcategory: 'loop',
    inputs: [{ name: 'Images', type: 'image', required: true }],
    outputs: [{ name: 'Image', type: 'image' }],
    status: 'soon',
  },
  {
    id: 'videoIteratorNode',
    label: 'Video Iterator',
    description: 'Video seti üzerinde döngü',
    icon: '🎬',
    category: 'iterators',
    subcategory: 'loop',
    inputs: [{ name: 'Videos', type: 'video', required: true }],
    outputs: [{ name: 'Video', type: 'video' }],
    status: 'soon',
  },

  // ── DATATYPES ─────────────────────────────────────────────────────────────────
  {
    id: 'numberNode',
    label: 'Number',
    description: 'Sayısal değer girişi',
    icon: '🔢',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Value', type: 'number' }],
    status: 'soon',
  },
  {
    id: 'textValueNode',
    label: 'Text',
    description: 'Serbest metin değer girişi',
    icon: '📝',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Value', type: 'text' }],
    status: 'soon',
  },
  {
    id: 'toggleNode',
    label: 'Toggle',
    description: 'Boolean aç/kapat değeri',
    icon: '🔘',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Value', type: 'boolean' }],
    status: 'soon',
  },
  {
    id: 'listSelectorNode',
    label: 'List Selector',
    description: 'Dropdown listeden seçim — kamera açısı, lens vb.',
    icon: '📋',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Value', type: 'text' }],
    status: 'soon',
  },
  {
    id: 'seedNode',
    label: 'Seed',
    description: 'Deterministic üretim için seed değeri',
    icon: '🎲',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Seed', type: 'number' }],
    status: 'soon',
  },
  {
    id: 'arrayNode',
    label: 'Array',
    description: 'Dizi / liste veri yapısı',
    icon: '📦',
    category: 'datatypes',
    subcategory: 'value',
    inputs: [],
    outputs: [{ name: 'Array', type: 'array' }],
    status: 'active',
  },
]

// ─── HELPERS ──────────────────────────────────────────────────────────────────

export function getNodesByCategory(category: NodeCategory): NodeDefinition[] {
  return NODE_DEFINITIONS.filter(n => n.category === category)
}

export function searchNodes(query: string): NodeDefinition[] {
  const q = query.toLowerCase()
  return NODE_DEFINITIONS.filter(n =>
    n.label.toLowerCase().includes(q) ||
    n.description.toLowerCase().includes(q) ||
    (n.provider?.toLowerCase().includes(q) ?? false)
  )
}

export function getNodeDef(id: string): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find(n => n.id === id)
}

// Active-only nodes that can be added to canvas
export const ACTIVE_NODE_IDS = new Set(
  NODE_DEFINITIONS.filter(n => n.status === 'active').map(n => n.id)
)

// Wire colors by data type (Weavy-style)
export const WIRE_COLORS: Record<NodeDataType, string> = {
  text:    '#a78bfa',  // purple
  image:   '#FFE744',  // yellow
  video:   '#D1FE17',  // green-yellow
  audio:   '#ec4899',  // pink
  mask:    '#94a3b8',  // grey
  number:  '#f97316',  // orange
  boolean: '#06b6d4',  // cyan
  array:   '#3b82f6',  // blue
  '3d':    '#06b6d4',  // cyan
  any:     '#6366f1',  // indigo
}
